Feature compiler checks
koebelt/GW-BASIC-Compiler pull request #2
Opened 2024-06-16 19:42 UTC by NicoStollFHWS

Support for:
- WHILE must be closed with WEND
- JUMPS only to existing Line numbers
- VARIABLES must be initialized

2024-06-17 15:23 UTC, koebelt requested changes
The Expression `jjtThis.jjtSetValue(t.image);` line 254, now 355, has been deleted and makes +/- operators unusable. Please revert this

2024-06-17 15:23 UTC, koebelt commented on src/Lexer.jjt
> +    Token t = new Token();
This token is never used so not needed

2024-06-17 15:23 UTC, koebelt commented on src/Lexer.jjt
> -    Term() ( (t=<PLUS> | t=<MINUS>) Term() )* { jjtThis.jjtSetValue(t.image); }
If you remove `jjtThis.jjtSetValue(t.image);` then no addition or substractions can be recognised,

**BREAKING CHANGE**

2024-06-17 16:48 UTC, NicoStollFHWS commented
Removed Token
Added jjtThis.jjtSetValue(t.image)
Added FOR Check

2024-06-18 09:30 UTC, koebelt approved these changes
LGTM, Ready to merge

2024-06-18 10:57 UTC, merged